-- ==================================================================
-- ARQUIVO: 01_schema.sql
-- DESCRIÇÃO: Estrutura DDL do Banco de Dados da Língua Kanoê
-- ==================================================================

-- 1. Tabela de Referências Bibliográficas
CREATE TABLE bibliografia (
  id_fonte BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  autores TEXT,
  ano INTEGER,
  tipo TEXT CHECK (tipo IN ('artigo','livro','relatorio','cartilha','tese','outro')) DEFAULT 'outro',
  arquivo_ref TEXT UNIQUE, -- Nome do arquivo PDF/Ref para integridade
  notas TEXT
);

-- 2. Tabela de Palavras (Lemas)
CREATE TABLE palavra (
  id_palavra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  termo_kanoe TEXT NOT NULL, -- A palavra principal
  classe_gramatical TEXT,    -- Ex: Substantivo, Verbo
  tags_nosql JSONB DEFAULT '{}'::jsonb -- Metadados extras flexíveis
);

-- 3. Tabela de Significados (Semântica)
CREATE TABLE significado (
  id_sentido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_palavra BIGINT NOT NULL REFERENCES palavra(id_palavra) ON DELETE CASCADE,
  traducao_primaria TEXT NOT NULL, -- Glosa em Português
  definicao_pt TEXT,               -- Definição secundária ou detalhada
  nota_cultural TEXT,              -- Contexto etnográfico
  fk_id_bibliografia BIGINT REFERENCES bibliografia(id_fonte)
);

-- 4. Tabela de Pronúncia (Formas e Fonética)
CREATE TABLE pronuncia (
  id_forma BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_id_palavra BIGINT NOT NULL REFERENCES palavra(id_palavra) ON DELETE CASCADE,
  grafia TEXT NOT NULL,      -- Grafia registrada
  ipa TEXT,                  -- Transcrição Fonética (IPA)
  tipo_forma TEXT,           -- 'padrao', 'variante', etc.
  morfologia JSONB DEFAULT '{}'::jsonb
);

-- 5. Tabela de Frases (Exemplos de Uso)
CREATE TABLE frase (
  id_frase BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto_kanoe TEXT NOT NULL,
  traducao_pt TEXT NOT NULL,
  contexto_uso TEXT,
  fk_id_palavra BIGINT REFERENCES palavra(id_palavra) ON DELETE CASCADE,
  fk_id_bibliografia BIGINT REFERENCES bibliografia(id_fonte)
);

-- Índices de Performance
CREATE INDEX idx_palavra_busca ON palavra USING GIN (to_tsvector('portuguese', termo_kanoe));
CREATE INDEX idx_significado_busca ON significado USING GIN (to_tsvector('portuguese', traducao_primaria));
